apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fullstack-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dev-Anamul/gitops-blog.git
    targetRevision: main
    path: environments/dev
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
