apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: blog-app
spec:
  serviceName: mongo-svc
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      automountServiceAccountToken: false
      containers:
        - name: mongodb
          image: mongo:8.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 200m
              memory: 1Gi
              ephemeral-storage: 1Gi
            limits:
              cpu: 500m
              memory: 2Gi
              ephemeral-storage: 2Gi
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
          envFrom:
            - secretRef:
                name: mongo-secret
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: standard
        resources:
          requests:
            storage: 5Gi
